### ISSUE TITLE
So how do you actually configure this plugin?

### ISSUE THREAD

**Issue by macco3k** [sharpSteff/lapce-csharp-plugin#2]
I've downloaded and extracted omnisharp in a dir under my home. But what should I set the configuration file to to make this plugin work? If I open the `.toml` config file I can see the following:

```toml
name = "csharp"
version = "1.1.0"
display-name = "C#"
author = "sharpSteff"
description = "C# for lapce using OmniSharp"
icon = "logo.png"
repository = "https://github.com/sharpSteff/lapce-csharp-plugin.git"
wasm = "target/wasm32-wasi/release/lapce-plugin-csharp.wasm"

[activation]
language = ["csharp"]
workspace-contains = [
    "*/*.csx",
    "*/*.cs",
    "*/*.sln",
    "*/omnisharp.json",
]

[config."volt.serverArgs"]
default = ["--languageserver"]
description = "LSP server arguments to pass when launching"

[config."volt.serverPath"]
default = ""
description = "Path to custom LSP executable"
```
What should I put into the `serverPath` setting?
